config/routes.rb
Rails.application.routes.draw do

    devise_for :users
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'homes#top'
      get 'home/about' => 'homes#about',as:'about'
      get 'search' => 'searches#search'
    resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
end
    resources :users do
      	resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
attachment :profile_image
          has_many :books, dependent: :destroy
          has_many :favorites, dependent: :destroy
          has_many :book_comments, dependent: :destroy
#自分がフォローされる
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
#自分がフォローする
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
#自分をフォローしている人。throughは、あるリレーションを他のテーブルを通して実現する際に用いる
has_many :followers, through: :reverse_of_relationships, source: :follower
#自分がフォローしている人
has_many :followings, through: :relationships, source: :followed

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

def follow(user_id)
    relationships.create(followed_id: user_id)
end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end



 def self.search(search,word)
      
      if search == "forward_match"
                      @user = User.where("name LIKE ?","#{word}%")
      elsif search == "backward_match"
                      @user = User.where("name LIKE ?","%#{word}")
      elsif search == "perfect_match"
                      @user = User.where(name: word)
      elsif search == "partial_match"
                      @user = User.where("name LIKE ?","%#{word}%")
      else
                      @user = User.all
      end
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def show
    @user =User.find(params[:id])
    @books =@user.books #ユーザーが投稿したbook（複数
    @book=Book.new

  end

  def edit
    @user =User.find(params[:id])
   if @user == current_user
    render "edit"
   else
    redirect_to user_path(current_user.id)
   end
  end



  def index
     @user = current_user
     @users = User.all
     @book = Book.new

  end

  def update
      @user = User.find(params[:id])

   if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
        redirect_to user_path(@user.id)
   else render :edit

   end

  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
 <% users.each do |user| %>
      <tr>
       <td> <%= attachment_image_tag user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %> </td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag current_user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
<% if current_user != user %>
<% if current_user.following?(user) %>
  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
<% end %>

<% else %>
 <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
<% end %>
 </div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<p id="notice"></p>
 <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>
  <div for="inputName">Name</div>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <div>image</div>
  <%= f.attachment_field :profile_image,autofocus: true, id:"inputimage", placeholder:"ファイルの選択"%>
  <div>introduction</div>
  <%= f.text_area :introduction, autofocus: true, id:"inputName"%>
  <div><%= f.submit "Update User", class: "btn btn-secondary" %></div>
  <% end %>
    </div>
   </div>
 </div>

app/views/users/index.html.erb
<%= render 'layouts/list',book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
<% @users.each do |user| %>
  <tr>
    <td> <%= attachment_image_tag current_user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %> </td>
     <td><%= user.name %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
      <td><%=link_to "Show",user_path(user.id)%></td>
  </tr>

<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/list',book: @book, user: @user %>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
  <% @books.each do |book| %>
  <tr>
    <td><%= link_to user_path(@user.id) do %> <%= attachment_image_tag book.user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %> <% end %></td>　
     <td><%=link_to book.title, book_path(book.id)%></td>
      <td><%= book.body %></td>
  </tr>
<% end %>

</tbody>
</table>
</div>
</div>
</div>