config/routes.rb
Rails.application.routes.draw do

    devise_for :users
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'homes#top'
      get 'home/about' => 'homes#about',as:'about'
      get 'search' => 'searches#search'
    resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
end
    resources :users do
      	resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end



end

app/models/book.rb
class Book < ApplicationRecord
     belongs_to :user
     has_many :favorites, dependent: :destroy
     has_many :book_comments, dependent: :destroy

     validates :title, presence: true
     validates :body, presence: true, length: { maximum: 200 }

     def favorited_by?(user)
         favorites.where(user_id: user.id).exists?
     end

def self.search(search, word)
        if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @book = Book.where(title: word)
        elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
        else
                        @book = Book.all
        end
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
      @books=Book.new
  end

  def create
     @book = Book.new(book_params)
     @book.user_id = current_user.id
     if @book.save
        flash[:notice]="You have created book successfully."
        redirect_to book_path(@book.id)
     else
        @user = current_user
        @books = Book.all
        render :index
     end
  end


  def index
     @books = Book.all
     @book = Book.new
     @user = current_user

  end

  def show
     @book = Book.new
     @books = Book.find(params[:id])
     @user = @books.user
     @book_comment = BookComment.new
  end

  def edit
     @book = Book.find(params[:id])
     if @book.user == current_user
    render "edit"
     else
    redirect_to books_path
     end
  
  end


  def destroy
     @book = Book.find(params[:id])
     @book.destroy
     redirect_to books_path
  end

  def update
     @book = Book.find(params[:id])
    if
      @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  private

  def book_params
    params.require(:book).permit( :title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/book_comments.html.erb
<table>
  <% @book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
  <tr>
    <td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= attachment_image_tag book_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    </td>
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: 'btn-sm btn-danger', method: :delete %></td>
    	<% end %>
  </tr>
  <% end %>
</table>
<%= form_with model:[@book,@book_comment], local: true do |f| %>
  <%= f.text_area :comment, size:"90x5" %><br>
  <%= f.submit '送信'%>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>

  <%= form_with model:@book, local:true do |f| %>
  <div for="inputName">Title</div>
  <%= f.text_field :title, autofocus: true, id:"inputName", placeholder:""%>


  <div>Opinion</div>
  <%= f.text_area :body, autofocus: true, id:"inputName"%>
  <div><%= f.submit "Update Book", class: "btn btn-success" %></div>

  <% end %>
  <%= link_to "Show", book_path(@book.id) %>
   |
  <%= link_to "Back", books_path %>

app/views/books/index.html.erb
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= render 'layouts/list',book: @book, user: @user %>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
<% @books.each do |book| %>
  <tr>
    <td> <%= link_to user_path(book.user.id)do %>
    <%= attachment_image_tag book.user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
    <% end %>
    </td>
      <td><%=link_to book.title, book_path(book.id)%></td>
      <td><%= book.body %></td>
      <td class="favorite"><%= render "favorites/favorite", book: book %></td>
      <td>コメント数: <%= book.book_comments.count %></td>
  </tr>

<% end %>
</tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<%= render 'layouts/list',book: @book, user: @user %>

<div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>

  		<table class="table">
  		  <tbody>

  		    <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                <%= @user.name%>
              <% end %>
            </td>

           <td><%=link_to @books.title, book_path(@books.id)%></td>
           <td><%= @books.body %></td>
           <td>コメント数: <%= @book.book_comments.count %></td>
           <td>
              <% if @books.user == current_user %>
                <td><%=link_to "Edit", edit_book_path(@books.id), class: "btn btn-sm btn-success" %> </td>
                <td><%= link_to "Destroy", book_path(@books.id), method: :delete, class: "btn btn-sm btn-danger" %></td>
              <% end %>
           </td>
          </tr>

      </tbody>
    </table>
</div>