config/routes.rb
Rails.application.routes.draw do

    devise_for :users
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'homes#top'
      get 'home/about' => 'homes#about',as:'about'
      get 'search' => 'searches#search'
    resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
end
    resources :users do
      	resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
     belongs_to :user
     has_many :favorites, dependent: :destroy
     has_many :book_comments, dependent: :destroy

     validates :title, presence: true
     validates :body, presence: true, length: { maximum: 200 }

     def favorited_by?(user)
         favorites.where(user_id: user.id).exists?
     end

def self.search(search, word)
        if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
        elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
        elsif search == "perfect_match"
                        @book = Book.where(title: word)
        elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
        else
                        @book = Book.all
        end
end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
	belongs_to :book
		validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates_uniqueness_of :book_id, scope: :user_id  #一つの投稿に対して１いいね

  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User" #follower_idカラムの値から、usersテーブルのレコードを参照できるようになる。


  belongs_to :followed, class_name: "User"#followed_idカラムの値から、usersテーブルのレコードを参照できるようになる。


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
attachment :profile_image
          has_many :books, dependent: :destroy
          has_many :favorites, dependent: :destroy
          has_many :book_comments, dependent: :destroy
#自分がフォローされる
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
#自分がフォローする
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
#自分をフォローしている人。throughは、あるリレーションを他のテーブルを通して実現する際に用いる
has_many :followers, through: :reverse_of_relationships, source: :follower
#自分がフォローしている人
has_many :followings, through: :relationships, source: :followed

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

def follow(user_id)
    relationships.create(followed_id: user_id)
end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end



 def self.search(search,word)
      
      if search == "forward_match"
                      @user = User.where("name LIKE ?","#{word}%")
      elsif search == "backward_match"
                      @user = User.where("name LIKE ?","%#{word}")
      elsif search == "perfect_match"
                      @user = User.where(name: word)
      elsif search == "partial_match"
                      @user = User.where("name LIKE ?","%#{word}%")
      else
                      @user = User.all
      end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!,except: [:top,:about]
protected

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
      @books=Book.new
  end

  def create
     @book = Book.new(book_params)
     @book.user_id = current_user.id
     if @book.save
        flash[:notice]="You have created book successfully."
        redirect_to book_path(@book.id)
     else
        @user = current_user
        @books = Book.all
        render :index
     end
  end


  def index
     @books = Book.all
     @book = Book.new
     @user = current_user

  end

  def show
     @book = Book.new
     @books = Book.find(params[:id])
     @user = @books.user
     @book_comment = BookComment.new
  end

  def edit
     @book = Book.find(params[:id])
     if @book.user == current_user
    render "edit"
     else
    redirect_to books_path
     end
  
  end


  def destroy
     @book = Book.find(params[:id])
     @book.destroy
     redirect_to books_path
  end

  def update
     @book = Book.find(params[:id])
    if
      @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  private

  def book_params
    params.require(:book).permit( :title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
    redirect_to request.referer

  end

  def destroy
     @book = Book.find(params[:book_id])
     favorite = @book.favorites.find_by(user_id: current_user.id)
     favorite.destroy
     redirect_to request.referer
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end 
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    search = params[:search]
    @word = params[:word]

    if @range == '1'
      p @range
      @user = User.search(search,@word)
p @user
    else
      @book = Book.search(search,@word)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def show
    @user =User.find(params[:id])
    @books =@user.books #ユーザーが投稿したbook（複数
    @book=Book.new

  end

  def edit
    @user =User.find(params[:id])
   if @user == current_user
    render "edit"
   else
    redirect_to user_path(current_user.id)
   end
  end



  def index
     @user = current_user
     @users = User.all
     @book = Book.new

  end

  def update
      @user = User.find(params[:id])

   if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
        redirect_to user_path(@user.id)
   else render :edit

   end

  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_list.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0" >
  <div class="row">

    <div class="col-md-3">

      <h2>User info</h2>
<%= attachment_image_tag user, :profile_image,  format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
<table class="table">
  <tbody>
    <tr></tr>
  <tr>
	  <td>name</td>
	  <td><%= user.name %></td>
  </tr>
  <tr>
	  <td>introduction</td>
	  <td><%= user.introduction %></td>
  </tr>
   <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
 </tbody>
</table>

<div class="row">
<%= link_to "",edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog"  %>
</div>

<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
  <h5>Title</h5>
  <%= f.text_field :title %>
  <h5>Opinion</h5>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book',class: "col-xs-12 btn btn-success" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <div class="container">
          <a class="navbar-brand p-3" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

     <% if user_signed_in? %>
       <li class="nav-item">
      <%= link_to 'Home', user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
      </li>

      <li>
       <%= link_to 'Users', users_path, class: "fas fa-users nav-link text-light" %>
      </li>

      <li>
       <%= link_to 'Books',books_path, class: "fas fa-book-open nav-link text-light"  %>
      </li>

      <li>
        <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light"  %>
      </li>


    <% else %>
    <li><%= link_to 'Home', root_path, class: "fas fa-home nav-link text-light" %></li>
    <li><%= link_to 'about', about_path, class: "fas fa-link nav-link text-light" %></li>
    <li><%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
    <li><%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt 'nav-link text-light" %></li>
    <% end %>
         </ul>
          </div>
        </div>
      </nav>
    </header>

<% if user_signed_in? %>
<%= form_with(url: search_path, method: :get,local:true) do |f| %>
<%= f.select :range ,[['---選択してください---',''], ['User','1'], ['Book','2']] %>
<%= f.select :search, [["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]] %>
<%= f.text_field (:word) %>
<%= f.submit "検索" %>
<% end %>
<% end %>

    <% if user_signed_in? %>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
<% end %>
  <%= yield %>

 <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
 </footer>

 </body>
</html>